In [1]:
import numpy as np

from sklearn.datasets import make_swiss_roll
X, t = make_swiss_roll(n_samples= 1000, noise =0.2, random_state=42)

In [2]:
# 8.3.2 실습 코드
X_centered = X - X.mean(axis=0)
U, s, Vt = np.linalg.svd(X_centered)
c1 = Vt.T[:, 0]
c2 = Vt.T[:, 1]

In [3]:
# 8.3.2 실습 코드 결과
print("X_centered : ", X)
print("c1 : ", c1, "c2 : ", c2)

X_centered :  [[-3.29677117  4.26198454  7.69787682]
 [ 5.95972743 11.45784273 12.72625276]
 [ 6.66051523 18.15820401 -9.84713337]
 ...
 [ 6.18364276  1.44095323 -1.71242696]
 [ 5.86076169  1.09185823 12.47091112]
 [-8.16213703  5.61235668  4.51171684]]
c1 :  [0.56791312 0.15670748 0.80803308] c2 :  [-0.77712377 -0.2213858   0.5891239 ]


In [5]:
# 8.3.4 실습코드
# 위의 numpy와 다른 점은 sklearn은 자동으로 센터에 맞춰줌
from sklearn.decomposition import PCA

pca = PCA(n_components = 2)
X2D = pca.fit_transform(X)

In [6]:
# 8.3.4 실습 코드 결과
print("pca : ", pca)
print("X2D : ", X2D)

pca :  PCA(n_components=2)
X2D :  [[  2.08374001   9.97769318]
 [ 12.53136592   4.15352368]
 [ -4.26069341 -11.17296129]
 ...
 [ -0.57812196  -2.30906044]
 [ 10.64441015   6.37488622]
 [ -3.04227432  11.58268844]]


In [7]:
# 8.3.5 실습 코드
pca.explained_variance_ratio_

array([0.40782396, 0.3020019 ])